In [2]:
# 27/10/2025

import numpy as np

# zeros (shape, dtype = float,int  , order = c)
data = np.zeros((3,3))
print(data)
print('----------------------------------------------------------')
data1 = np.zeros((3,3), dtype = int)
print(data1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------------------------------------------------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
# ones (shape, dtype = none)

data = np.ones((2,4))
print(data)
data.ndim

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2

In [14]:
# full

data = np.full((2, 3), 5)           # 2x3 array with all values = 5
print(data)
data.ndim

[[5 5 5]
 [5 5 5]]


2

In [16]:
# identity

data = np.identity(4,dtype = int)    # it generates the random numbers
print(data)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [20]:
# Reshaping (used to reshape the rows and columns)

arr = np.arange(12)
print(arr)
re_arr = np.reshape(arr,(2,6))
print(re_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [21]:
arr = np.arange(24).reshape(3,2,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [22]:
# Swaps  (Swaps the axes (rows and columns) of an array — useful for 2D/3D arrays.)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

swapped = np.swapaxes(arr, 0, 1)
print(swapped)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# concatenate (used to merge the arrays)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print(c)